Traceback (most recent call last):
  File "c:\users\skywater\pycharmprojects\personal\demo\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "c:\users\skywater\pycharmprojects\personal\demo\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\skywater\pycharmprojects\personal\demo\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\skywater\pycharmprojects\personal\demo\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\skywater\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\users\skywater\pycharmprojects\personal\demo\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "c:\users\skywater\pycharmprojects\personal\demo\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\skywater\pycharmprojects\personal\demo\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
plt.style.use('https://raw.githubusercontent.com/datawhalechina/fantastic-matplotlib/main/file/presentation.mplstyle')
plt.plot([1,2,3,4],[2,3,4,5]);
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mgaierror[0m                                  Traceback (most recent call last)
[1;32m~\AppData\Local\Programs\Python\Python39\lib\urllib\request.py[0m in [0;36mdo_open[1;34m(self, http_class, req, **http_conn_args)[0m
[0;32m   1345[0m             [1;32mtry[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1346[1;33m                 h.request(req.get_method(), req.selector, req.data, headers,
[0m[0;32m   1347[0m                           encode_chunked=req.has_header('Transfer-encoding'))

[1;32m~\AppData\Local\Programs\Python\Python39\lib\http\client.py[0m in [0;36mrequest[1;34m(self, method, url, body, headers, encode_chunked)[0m
[0;32m   1252[0m         [1;34m"""Send a complete request to the server."""[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1253[1;33m         [0mself[0m[1;33m.[0m[0m_send_request[0m[1;33m([0m[0mmethod[0m[1;33m,[0m [0murl[0m[1;33m,[0m [0mbody[0m[1;33m,[0m [0mheaders[0m[1;33m,[0m [0mencode_chunked[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1254[0m [1;33m[0m[0m

[1;32m~\AppData\Local\Programs\Python\Python39\lib\http\client.py[0m in [0;36m_send_request[1;34m(self, method, url, body, headers, encode_chunked)[0m
[0;32m   1298[0m             [0mbody[0m [1;33m=[0m [0m_encode[0m[1;33m([0m[0mbody[0m[1;33m,[0m [1;34m'body'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1299[1;33m         [0mself[0m[1;33m.[0m[0mendheaders[0m[1;33m([0m[0mbody[0m[1;33m,[0m [0mencode_chunked[0m[1;33m=[0m[0mencode_chunked[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1300[0m [1;33m[0m[0m

[1;32m~\AppData\Local\Programs\Python\Python39\lib\http\client.py[0m in [0;36mendheaders[1;34m(self, message_body, encode_chunked)[0m
[0;32m   1247[0m             [1;32mraise[0m [0mCannotSendHeader[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1248[1;33m         [0mself[0m[1;33m.[0m[0m_send_output[0m[1;33m([0m[0mmessage_body[0m[1;33m,[0m [0mencode_chunked[0m[1;33m=[0m[0mencode_chunked[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1249[0m [1;33m[0m[0m

[1;32m~\AppData\Local\Programs\Python\Python39\lib\http\client.py[0m in [0;36m_send_output[1;34m(self, message_body, encode_chunked)[0m
[0;32m   1007[0m         [1;32mdel[0m [0mself[0m[1;33m.[0m[0m_buffer[0m[1;33m[[0m[1;33m:[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1008[1;33m         [0mself[0m[1;33m.[0m[0msend[0m[1;33m([0m[0mmsg[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1009[0m [1;33m[0m[0m

[1;32m~\AppData\Local\Programs\Python\Python39\lib\http\client.py[0m in [0;36msend[1;34m(self, data)[0m
[0;32m    947[0m             [1;32mif[0m [0mself[0m[1;33m.[0m[0mauto_open[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 948[1;33m                 [0mself[0m[1;33m.[0m[0mconnect[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    949[0m             [1;32melse[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\AppData\Local\Programs\Python\Python39\lib\http\client.py[0m in [0;36mconnect[1;34m(self)[0m
[0;32m   1414[0m [1;33m[0m[0m
[1;32m-> 1415[1;33m             [0msuper[0m[1;33m([0m[1;33m)[0m[1;33m.[0m[0mconnect[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1416[0m [1;33m[0m[0m

[1;32m~\AppData\Local\Programs\Python\Python39\lib\http\client.py[0m in [0;36mconnect[1;34m(self)[0m
[0;32m    918[0m         [1;34m"""Connect to the host and port specified in __init__."""[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 919[1;33m         self.sock = self._create_connection(
[0m[0;32m    920[0m             (self.host,self.port), self.timeout, self.source_address)

[1;32m~\AppData\Local\Programs\Python\Python39\lib\socket.py[0m in [0;36mcreate_connection[1;34m(address, timeout, source_address)[0m
[0;32m    821[0m     [0merr[0m [1;33m=[0m [1;32mNone[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 822[1;33m     [1;32mfor[0m [0mres[0m [1;32min[0m [0mgetaddrinfo[0m[1;33m([0m[0mhost[0m[1;33m,[0m [0mport[0m[1;33m,[0m [1;36m0[0m[1;33m,[0m [0mSOCK_STREAM[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    823[0m         [0maf[0m[1;33m,[0m [0msocktype[0m[1;33m,[0m [0mproto[0m[1;33m,[0m [0mcanonname[0m[1;33m,[0m [0msa[0m [1;33m=[0m [0mres[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\AppData\Local\Programs\Python\Python39\lib\socket.py[0m in [0;36mgetaddrinfo[1;34m(host, port, family, type, proto, flags)[0m
[0;32m    952[0m     [0maddrlist[0m [1;33m=[0m [1;33m[[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 953[1;33m     [1;32mfor[0m [0mres[0m [1;32min[0m [0m_socket[0m[1;33m.[0m[0mgetaddrinfo[0m[1;33m([0m[0mhost[0m[1;33m,[0m [0mport[0m[1;33m,[0m [0mfamily[0m[1;33m,[0m [0mtype[0m[1;33m,[0m [0mproto[0m[1;33m,[0m [0mflags[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    954[0m         [0maf[0m[1;33m,[0m [0msocktype[0m[1;33m,[0m [0mproto[0m[1;33m,[0m [0mcanonname[0m[1;33m,[0m [0msa[0m [1;33m=[0m [0mres[0m[1;33m[0m[1;33m[0m[0m

[1;31mgaierror[0m: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

[1;31mURLError[0m                                  Traceback (most recent call last)
[1;32mc:\users\skywater\pycharmprojects\personal\demo\lib\site-packages\matplotlib\style\core.py[0m in [0;36muse[1;34m(style)[0m
[0;32m    114[0m             [1;32mtry[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 115[1;33m                 [0mrc[0m [1;33m=[0m [0mrc_params_from_file[0m[1;33m([0m[0mstyle[0m[1;33m,[0m [0muse_default_template[0m[1;33m=[0m[1;32mFalse[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    116[0m                 [0m_apply_style[0m[1;33m([0m[0mrc[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32mc:\users\skywater\pycharmprojects\personal\demo\lib\site-packages\matplotlib\__init__.py[0m in [0;36mrc_params_from_file[1;34m(fname, fail_on_error, use_default_template)[0m
[0;32m    797[0m     """
[1;32m--> 798[1;33m     [0mconfig_from_file[0m [1;33m=[0m [0m_rc_params_in_file[0m[1;33m([0m[0mfname[0m[1;33m,[0m [0mfail_on_error[0m[1;33m=[0m[0mfail_on_error[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    799[0m [1;33m[0m[0m

[1;32mc:\users\skywater\pycharmprojects\personal\demo\lib\site-packages\matplotlib\__init__.py[0m in [0;36m_rc_params_in_file[1;34m(fname, transform, fail_on_error)[0m
[0;32m    726[0m     [0mrc_temp[0m [1;33m=[0m [1;33m{[0m[1;33m}[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 727[1;33m     [1;32mwith[0m [0m_open_file_or_url[0m[1;33m([0m[0mfname[0m[1;33m)[0m [1;32mas[0m [0mfd[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    728[0m         [1;32mtry[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\AppData\Local\Programs\Python\Python39\lib\contextlib.py[0m in [0;36m__enter__[1;34m(self)[0m
[0;32m    116[0m         [1;32mtry[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 117[1;33m             [1;32mreturn[0m [0mnext[0m[1;33m([0m[0mself[0m[1;33m.[0m[0mgen[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    118[0m         [1;32mexcept[0m [0mStopIteration[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32mc:\users\skywater\pycharmprojects\personal\demo\lib\site-packages\matplotlib\__init__.py[0m in [0;36m_open_file_or_url[1;34m(fname)[0m
[0;32m    697[0m             )
[1;32m--> 698[1;33m         [1;32mwith[0m [0murllib[0m[1;33m.[0m[0mrequest[0m[1;33m.[0m[0murlopen[0m[1;33m([0m[0mfname[0m[1;33m,[0m [0mcontext[0m[1;33m=[0m[0mssl_ctx[0m[1;33m)[0m [1;32mas[0m [0mf[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    699[0m             [1;32myield[0m [1;33m([0m[0mline[0m[1;33m.[0m[0mdecode[0m[1;33m([0m[1;34m'utf-8'[0m[1;33m)[0m [1;32mfor[0m [0mline[0m [1;32min[0m [0mf[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\AppData\Local\Programs\Python\Python39\lib\urllib\request.py[0m in [0;36murlopen[1;34m(url, data, timeout, cafile, capath, cadefault, context)[0m
[0;32m    213[0m         [0mopener[0m [1;33m=[0m [0m_opener[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 214[1;33m     [1;32mreturn[0m [0mopener[0m[1;33m.[0m[0mopen[0m[1;33m([0m[0murl[0m[1;33m,[0m [0mdata[0m[1;33m,[0m [0mtimeout[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    215[0m [1;33m[0m[0m

[1;32m~\AppData\Local\Programs\Python\Python39\lib\urllib\request.py[0m in [0;36mopen[1;34m(self, fullurl, data, timeout)[0m
[0;32m    516[0m         [0msys[0m[1;33m.[0m[0maudit[0m[1;33m([0m[1;34m'urllib.Request'[0m[1;33m,[0m [0mreq[0m[1;33m.[0m[0mfull_url[0m[1;33m,[0m [0mreq[0m[1;33m.[0m[0mdata[0m[1;33m,[0m [0mreq[0m[1;33m.[0m[0mheaders[0m[1;33m,[0m [0mreq[0m[1;33m.[0m[0mget_method[0m[1;33m([0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 517[1;33m         [0mresponse[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0m_open[0m[1;33m([0m[0mreq[0m[1;33m,[0m [0mdata[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    518[0m [1;33m[0m[0m

[1;32m~\AppData\Local\Programs\Python\Python39\lib\urllib\request.py[0m in [0;36m_open[1;34m(self, req, data)[0m
[0;32m    533[0m         [0mprotocol[0m [1;33m=[0m [0mreq[0m[1;33m.[0m[0mtype[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 534[1;33m         result = self._call_chain(self.handle_open, protocol, protocol +
[0m[0;32m    535[0m                                   '_open', req)

[1;32m~\AppData\Local\Programs\Python\Python39\lib\urllib\request.py[0m in [0;36m_call_chain[1;34m(self, chain, kind, meth_name, *args)[0m
[0;32m    493[0m             [0mfunc[0m [1;33m=[0m [0mgetattr[0m[1;33m([0m[0mhandler[0m[1;33m,[0m [0mmeth_name[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 494[1;33m             [0mresult[0m [1;33m=[0m [0mfunc[0m[1;33m([0m[1;33m*[0m[0margs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    495[0m             [1;32mif[0m [0mresult[0m [1;32mis[0m [1;32mnot[0m [1;32mNone[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\AppData\Local\Programs\Python\Python39\lib\urllib\request.py[0m in [0;36mhttps_open[1;34m(self, req)[0m
[0;32m   1388[0m         [1;32mdef[0m [0mhttps_open[0m[1;33m([0m[0mself[0m[1;33m,[0m [0mreq[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1389[1;33m             return self.do_open(http.client.HTTPSConnection, req,
[0m[0;32m   1390[0m                 context=self._context, check_hostname=self._check_hostname)

[1;32m~\AppData\Local\Programs\Python\Python39\lib\urllib\request.py[0m in [0;36mdo_open[1;34m(self, http_class, req, **http_conn_args)[0m
[0;32m   1348[0m             [1;32mexcept[0m [0mOSError[0m [1;32mas[0m [0merr[0m[1;33m:[0m [1;31m# timeout error[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1349[1;33m                 [1;32mraise[0m [0mURLError[0m[1;33m([0m[0merr[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1350[0m             [0mr[0m [1;33m=[0m [0mh[0m[1;33m.[0m[0mgetresponse[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mURLError[0m: <urlopen error [Errno 11004] getaddrinfo failed>

The above exception was the direct cause of the following exception:

[1;31mOSError[0m                                   Traceback (most recent call last)
[1;32m<ipython-input-5-8ce8ec49641e>[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [0mplt[0m[1;33m.[0m[0mstyle[0m[1;33m.[0m[0muse[0m[1;33m([0m[1;34m'https://raw.githubusercontent.com/datawhalechina/fantastic-matplotlib/main/file/presentation.mplstyle'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [0mplt[0m[1;33m.[0m[0mplot[0m[1;33m([0m[1;33m[[0m[1;36m1[0m[1;33m,[0m[1;36m2[0m[1;33m,[0m[1;36m3[0m[1;33m,[0m[1;36m4[0m[1;33m][0m[1;33m,[0m[1;33m[[0m[1;36m2[0m[1;33m,[0m[1;36m3[0m[1;33m,[0m[1;36m4[0m[1;33m,[0m[1;36m5[0m[1;33m][0m[1;33m)[0m[1;33m;[0m[1;33m[0m[1;33m[0m[0m

[1;32mc:\users\skywater\pycharmprojects\personal\demo\lib\site-packages\matplotlib\style\core.py[0m in [0;36muse[1;34m(style)[0m
[0;32m    116[0m                 [0m_apply_style[0m[1;33m([0m[0mrc[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    117[0m             [1;32mexcept[0m [0mIOError[0m [1;32mas[0m [0merr[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 118[1;33m                 raise IOError(
[0m[0;32m    119[0m                     [1;34m"{!r} not found in the style library and input is not a "[0m[1;33m[0m[1;33m[0m[0m
[0;32m    120[0m                     [1;34m"valid URL or path; see `style.available` for list of "[0m[1;33m[0m[1;33m[0m[0m

[1;31mOSError[0m: 'https://raw.githubusercontent.com/datawhalechina/fantastic-matplotlib/main/file/presentation.mplstyle' not found in the style library and input is not a valid URL or path; see `style.available` for list of available styles
OSError: 'https://raw.githubusercontent.com/datawhalechina/fantastic-matplotlib/main/file/presentation.mplstyle' not found in the style library and input is not a valid URL or path; see `style.available` for list of available styles

